### ISSUE TITLE
Link and its label IDs should have more meaningful names

### ISSUE THREAD

**Issue by FloSch62** [srl-labs/clab-io-draw#4]
A meaningful ID, would help to create grafana dashboards, with the flowchart plugin.

    <mxCell id="6955bd28e4f532e5d3c134ab6a0aed99-trgt" value="e1-32" style="labelBackgroundColor=#ffffff;;" parent="6955bd28e4f532e5d3c134ab6a0aed99" vertex="1" connectable="0">
<mxGeometry x="0.5" relative="-1" as="geometry">
<mxPoint as="offset" />
</mxGeometry>
</mxCell>

**Comment by sacckth** [comment]
```<mxCell id="link_id:leaf2:e1-2:client4:eth1-src" value="e1-2" style="labelBackgroundColor=#ffffff;;" parent="link_id:leaf2:e1-2:client4:eth1" vertex="1" connectable="0">```
